### ISSUE TITLE
Automatic number of rows?

### ISSUE THREAD

**Issue by valpackett** [chris-l/bin-packing-grid#5]
I'm searching for a masonry-like web component now, and a lot of them are Polymer 0.x based... yours doesn't depend on Polymer, which works fine in a 1.0 app.

Unfortunately, seems like it requires `rows="N"` on all of the elements which makes it kinda pointless. I need to display news articles in a bin-packed grid – I don't know the heights of the elements!

**Comment by chris-l** [comment]
Hi!
Well yes, I understand, but the problem is, how `bin-packing-item` will know the height of the element?
If the content is an image, it could just load it using `new Image()` and then get the `height`. But what if it is just text? Should it just try to get the default height of the full text and adjust to that? But what if some people would prefer to have longer text and add an scroll bar after certain maximum size?
What if it is an image, but the image is large, and you want to resize it inside?

I'm trying to keep `bin-packing-item` really generic and not taking guesses of what is inside of the element.

The thing that perhaps could be done, is to add to `bin-packing-grid` the possibility that the user can add a function to calculate the number of rows.

In such way, at the time to set the size of each `bin-packing-item` element, if it doesn't have the `rows` attribute, it will check if the parent (the `bin-packing-grid`) has a `getRows` function created by the user.

If indeed it does have it, it will execute that function passing the `bin-packing-item` element as `this`. That way, the user can do whatever he wants to determine the amount of `rows` of the elements.

The function must return the height of the element in amount of `cellSize`.

I'm thinking about this. I'm not sure yet, but so far, sounds like a good idea.

**Comment by valpackett** [comment]
Well, `bin-packing-item` knows the width. Just let the elements render with `height: auto` and get the resulting heights!

If the user wants a scroll bar, they will use `max-height` and `overflow-y: auto`. For the images, `max-width: 100%` should already be used everywhere. etc. _Everything the user wants_ is already solved by normal CSS.

Have you seen [masonry](http://masonry.desandro.com/)?

**Comment by chris-l** [comment]
Actually, getting the default height of the element sounds like a good idea for a default `getRows` function. (but I definitely would give the user the ability to override it) Once I have time, I could implement that function.

**Comment by chris-l** [comment]
Well, is done. Now it has a new attribute `detect-size`. Using it, it detects and sets how many `rows` and `cols` are required by the content of the `bin-packing-item`.
